Measure steady state requests per second
To demonstrate how JRuby and Rubinius perform with
warm JITs. JRuby takes ~10 minutes to warm up,
Rubinius takes just under ~15 minutes.

diff --git a/isrubyfastyet/runner/scripts/run_benchmark b/isrubyfastyet/runner/scripts/run_benchmark
--- a/isrubyfastyet/runner/scripts/run_benchmark
+++ b/isrubyfastyet/runner/scripts/run_benchmark
@@ -23,8 +23,8 @@ then
 	echo "$4"
 	eval "$4"
 
-	# timeout the benchmark after 15 minutes or so
-	eval "(gtimeout --kill-after=5 900 $3 $5 || echo 'failed') | tail -1 > $6"
+	# timeout the benchmark after 20 minutes or so
+	eval "(gtimeout --kill-after=5 1200 $3 $5 || echo 'failed') | tail -1 > $6"
 else
 	echo "rvm failed to switch to $2" > $6
 	exit 1
