Log error in results if RVM failed to switch (e.g. if ruby install failed)

diff --git a/runner/scripts/ruby_version_in_rvm b/runner/scripts/ruby_version_in_rvm
--- a/runner/scripts/ruby_version_in_rvm
+++ b/runner/scripts/ruby_version_in_rvm
@@ -4,5 +4,10 @@
 
 source "$HOME/.rvm/scripts/rvm"
 
-rvm "$1"
-eval "$2 -v"
+if rvm "$1"
+then
+	eval "$2 -v"
+else
+	echo "rvm failed to switch to $1"
+	exit 1
+fi
diff --git a/runner/scripts/run_benchmark b/runner/scripts/run_benchmark
--- a/runner/scripts/run_benchmark
+++ b/runner/scripts/run_benchmark
@@ -7,14 +7,18 @@ source "$HOME/.rvm/scripts/rvm"
 cd "$1"
 pwd
 
-rvm "$2@benchmark"
+if rvm "$2@benchmark"
+then
+	echo 'Sleeping 30 seconds to let the system cool off...'
+	sleep 30
 
-echo 'Sleeping 30 seconds to let the system cool off...'
-sleep 30
+	export RUBY_COMMAND="$3"
 
-export RUBY_COMMAND="$3"
+	echo "benchmarking..."
+	echo "$RUBY_COMMAND ($2)"
 
-echo "benchmarking..."
-echo "$RUBY_COMMAND ($2)"
-
-eval "($3 $4 || echo 'failed') | tail -1 > $5"
+	eval "($3 $4 || echo 'failed') | tail -1 > $5"
+else
+	echo "rvm failed to switch to $2" > $5
+	exit 1
+fi
