Make ruby version grabbing more robust

diff --git a/runner/scripts/ruby_version_in_rvm b/runner/scripts/ruby_version_in_rvm
--- a/runner/scripts/ruby_version_in_rvm
+++ b/runner/scripts/ruby_version_in_rvm
@@ -6,7 +6,11 @@ source "$HOME/.rvm/scripts/rvm"
 
 if rvm "$1"
 then
-	eval "$2 -v"
+	if ! eval "$2 -v"
+	then
+  	echo "command failed: $2 -v"
+  	exit 1
+  fi
 else
 	echo "rvm failed to switch to $1"
 	exit 1
