Get everything working properly--3 benchmarks: memory, requests per second, and startup time (but doesn't work on MacRuby or Maglev)

diff --git a/runner/scripts/run_benchmark b/runner/scripts/run_benchmark
--- a/runner/scripts/run_benchmark
+++ b/runner/scripts/run_benchmark
@@ -1,44 +1,17 @@
 #!/usr/bin/env bash
 
+# run_benchmark <benchmark_folder> <rvm_command> <ruby_command> <benchmark_file> <result_file>
+
 source "$HOME/.rvm/scripts/rvm"
 
 cd "$1"
+pwd
 
-rvm get latest
-rvm reload
+rvm "$2@benchmark"
 
-rvm "$2@benchmark" --create || rvm install "$2" && rvm "$2@benchmark" --create
+export RUBY_COMMAND="$3"
 
-which bundle || gem install bundler
+echo "benchmarking..."
+echo "$RUBY_COMMAND ($2)"
 
-if [ -e "Gemfile.lock" ]
-then
-    rm Gemfile.lock
-fi
-
-if [ -e "Gemfile_$2.lock" ]
-then
-    cp "Gemfile_$2.lock" "Gemfile.lock"
-fi
-
-bundle install
-
-if [ -e "Gemfile_$2.lock" ]
-then
-    rm "Gemfile_$2.lock"
-fi
-
-cp Gemfile.lock "Gemfile_$2.lock"
-
-if [ -e results.txt ]
-then
-    rm results.txt
-fi
-
-# warmup
-eval "$3 benchmark.rb > /dev/null"
-
-for n in 1 2 3 4
-do
-    eval "$3 benchmark.rb >> results.txt"
-done
+eval "($3 $4 || echo 'failed') | tail -1 > $5"
